---
# Source: matrum/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: name-matrum
  labels:
    helm.sh/chart: matrum-0.1.0
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: matrum/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: very-secret
type: Opaque
data:
  homeserver.yml: IyB2aW06ZnQ9eWFtbAoKIyMgU2VydmVyICMjCgpzZXJ2ZXJfbmFtZTogIm5vcmRpc2NoLmNoYXQiCnBpZF9maWxlOiAvaG9tZXNlcnZlci5waWQKd2ViX2NsaWVudDogRmFsc2UKc29mdF9maWxlX2xpbWl0OiAwCmxvZ19jb25maWc6ICIvY29uZmlnL2xvZy5jb25maWcueW1sIgoKIyMgUG9ydHMgIyMKCmxpc3RlbmVyczoKICAtIHBvcnQ6IDgwMDgKICAgIHRsczogZmFsc2UKICAgIGJpbmRfYWRkcmVzc2VzOiBbJzo6J10KICAgIHR5cGU6IGh0dHAKICAgIHhfZm9yd2FyZGVkOiBmYWxzZQoKICAgIHJlc291cmNlczoKICAgICAgLSBuYW1lczogW2NsaWVudF0KICAgICAgICBjb21wcmVzczogdHJ1ZQogICAgICAtIG5hbWVzOiBbZmVkZXJhdGlvbl0KICAgICAgICBjb21wcmVzczogZmFsc2UKCiMjIERhdGFiYXNlICMjCgpkYXRhYmFzZToKICBuYW1lOiAic3FsaXRlMyIKICBhcmdzOgogICAgZGF0YWJhc2U6ICIvZGF0YS9ob21lc2VydmVyLmRiIgoKCiMjIFBlcmZvcm1hbmNlICMjCgpldmVudF9jYWNoZV9zaXplOiAiMTBLIgoKIyMgUmF0ZWxpbWl0aW5nICMjCgpyY19tZXNzYWdlc19wZXJfc2Vjb25kOiAwLjIKcmNfbWVzc2FnZV9idXJzdF9jb3VudDogMTAuMApmZWRlcmF0aW9uX3JjX3dpbmRvd19zaXplOiAxMDAwCmZlZGVyYXRpb25fcmNfc2xlZXBfbGltaXQ6IDEwCmZlZGVyYXRpb25fcmNfc2xlZXBfZGVsYXk6IDUwMApmZWRlcmF0aW9uX3JjX3JlamVjdF9saW1pdDogNTAKZmVkZXJhdGlvbl9yY19jb25jdXJyZW50OiAzCgojIyBGaWxlcyAjIwoKbWVkaWFfc3RvcmVfcGF0aDogIi9kYXRhL21lZGlhIgp1cGxvYWRzX3BhdGg6ICIvZGF0YS91cGxvYWRzIgptYXhfdXBsb2FkX3NpemU6ICI1MDBNIgptYXhfaW1hZ2VfcGl4ZWxzOiAiNjRNIgpkeW5hbWljX3RodW1ibmFpbHM6IGZhbHNlCgojIExpc3Qgb2YgdGh1bWJuYWlsIHRvIHByZWNhbGN1bGF0ZSB3aGVuIGFuIGltYWdlIGlzIHVwbG9hZGVkLgp0aHVtYm5haWxfc2l6ZXM6CiAgLSB3aWR0aDogMzIKICAgIGhlaWdodDogMzIKICAgIG1ldGhvZDogY3JvcAogIC0gd2lkdGg6IDk2CiAgICBoZWlnaHQ6IDk2CiAgICBtZXRob2Q6IGNyb3AKICAtIHdpZHRoOiAzMjAKICAgIGhlaWdodDogMjQwCiAgICBtZXRob2Q6IHNjYWxlCiAgLSB3aWR0aDogNjQwCiAgICBoZWlnaHQ6IDQ4MAogICAgbWV0aG9kOiBzY2FsZQogIC0gd2lkdGg6IDgwMAogICAgaGVpZ2h0OiA2MDAKICAgIG1ldGhvZDogc2NhbGUKCnVybF9wcmV2aWV3X2VuYWJsZWQ6IEZhbHNlCm1heF9zcGlkZXJfc2l6ZTogIjEwTSIKCiMjIENhcHRjaGEgIyMKCgpyZWNhcHRjaGFfcHVibGljX2tleTogIllPVVJfUFVCTElDX0tFWSIKcmVjYXB0Y2hhX3ByaXZhdGVfa2V5OiAiWU9VUl9QUklWQVRFX0tFWSIKZW5hYmxlX3JlZ2lzdHJhdGlvbl9jYXB0Y2hhOiBGYWxzZQpyZWNhcHRjaGFfc2l0ZXZlcmlmeV9hcGk6ICJodHRwczovL3d3dy5nb29nbGUuY29tL3JlY2FwdGNoYS9hcGkvc2l0ZXZlcmlmeSIKCgojIyBUdXJuICMjCgoKdHVybl91cmlzOiBbXQp0dXJuX3NoYXJlZF9zZWNyZXQ6ICJZT1VSX1NIQVJFRF9TRUNSRVQiCnR1cm5fdXNlcl9saWZldGltZTogIjFoIgp0dXJuX2FsbG93X2d1ZXN0czogVHJ1ZQoKCiMjIFJlZ2lzdHJhdGlvbiAjIwoKZW5hYmxlX3JlZ2lzdHJhdGlvbjogRmFsc2UKcmVnaXN0cmF0aW9uX3NoYXJlZF9zZWNyZXQ6ICIzYmE3NWI5MTNjZTA3MWZlYmRmZjRmOTVlODUyMTY1MDU3ODA5ZDE1MzhkZDA1ZWIxNzg3MzhjNGY2YjBjOGI2IgpiY3J5cHRfcm91bmRzOiAxMgphbGxvd19ndWVzdF9hY2Nlc3M6IEZhbHNlCmVuYWJsZV9ncm91cF9jcmVhdGlvbjogdHJ1ZQoKIyBUaGUgbGlzdCBvZiBpZGVudGl0eSBzZXJ2ZXJzIHRydXN0ZWQgdG8gdmVyaWZ5IHRoaXJkIHBhcnR5CiMgaWRlbnRpZmllcnMgYnkgdGhpcyBzZXJ2ZXIuCiMKIyBBbHNvIGRlZmluZXMgdGhlIElEIHNlcnZlciB3aGljaCB3aWxsIGJlIGNhbGxlZCB3aGVuIGFuIGFjY291bnQgaXMKIyBkZWFjdGl2YXRlZCAob25lIHdpbGwgYmUgcGlja2VkIGFyYml0cmFyaWx5KS4KdHJ1c3RlZF90aGlyZF9wYXJ0eV9pZF9zZXJ2ZXJzOgogIC0gbWF0cml4Lm9yZwogIC0gdmVjdG9yLmltCgojIyBNZXRyaWNzICMjIwoKCmVuYWJsZV9tZXRyaWNzOiBGYWxzZQpyZXBvcnRfc3RhdHM6IEZhbHNlCgoKIyMgQVBJIENvbmZpZ3VyYXRpb24gIyMKCnJvb21faW52aXRlX3N0YXRlX3R5cGVzOgogIC0gIm0ucm9vbS5qb2luX3J1bGVzIgogIC0gIm0ucm9vbS5jYW5vbmljYWxfYWxpYXMiCiAgLSAibS5yb29tLmF2YXRhciIKICAtICJtLnJvb20ubmFtZSIKCgphcHBfc2VydmljZV9jb25maWdfZmlsZXM6IFtdCgoKbWFjYXJvb25fc2VjcmV0X2tleTogImQ1YTFkZmE0OTI1Yzc3YmU4MmU0MDc1N2M0NjkzOTE2YWRmOGZkNWVmMTBiOTA3NTJjM2VjZWE0ZjNmZmU5NmUiCmV4cGlyZV9hY2Nlc3NfdG9rZW46IEZhbHNlCgojIyBTaWduaW5nIEtleXMgIyMKCnNpZ25pbmdfa2V5X3BhdGg6ICIvY29uZmlnL25vcmRpc2NoLmNoYXQuc2lnbmluZy5rZXkiCm9sZF9zaWduaW5nX2tleXM6IHt9CmtleV9yZWZyZXNoX2ludGVydmFsOiAiMWQiICMgMSBEYXkuCgojIFRoZSB0cnVzdGVkIHNlcnZlcnMgdG8gZG93bmxvYWQgc2lnbmluZyBrZXlzIGZyb20uCnBlcnNwZWN0aXZlczoKICBzZXJ2ZXJzOgogICAgIm1hdHJpeC5vcmciOgogICAgICB2ZXJpZnlfa2V5czoKICAgICAgICAiZWQyNTUxOTphdXRvIjoKICAgICAgICAgIGtleTogIk5vaTZXcWNEajBRbVB4Q05RcWdlendUbEJLcmZxZWhZMXUyRnlXUDl1WXciCgpwYXNzd29yZF9jb25maWc6CiAgZW5hYmxlZDogdHJ1ZQ==
  log.config.yml: dmVyc2lvbjogMQoKZm9ybWF0dGVyczoKICBwcmVjaXNlOgogICAgZm9ybWF0OiAnJShhc2N0aW1lKXMgLSAlKG5hbWUpcyAtICUobGluZW5vKWQgLSAlKGxldmVsbmFtZSlzIC0gJShyZXF1ZXN0KXMgLSAlKG1lc3NhZ2UpcycKCmhhbmRsZXJzOgogIGNvbnNvbGU6CiAgICBjbGFzczogbG9nZ2luZy5TdHJlYW1IYW5kbGVyCiAgICBmb3JtYXR0ZXI6IHByZWNpc2UKCmxvZ2dlcnM6CiAgc3luYXBzZS5zdG9yYWdlLlNRTDoKICAgICMgYmV3YXJlOiBpbmNyZWFzaW5nIHRoaXMgdG8gREVCVUcgd2lsbCBtYWtlIHN5bmFwc2UgbG9nIHNlbnNpdGl2ZQogICAgIyBpbmZvcm1hdGlvbiBzdWNoIGFzIGFjY2VzcyB0b2tlbnMuCiAgICBsZXZlbDogSU5GTwoKcm9vdDoKICBsZXZlbDogSU5GTwogIGhhbmRsZXJzOiBbY29uc29sZV0KCmRpc2FibGVfZXhpc3RpbmdfbG9nZ2VyczogZmFsc2U=
  nordisch.chat.macaroon.key: ZDVhMWRmYTQ5MjVjNzdiZTgyZTQwNzU3YzQ2OTM5MTZhZGY4ZmQ1ZWYxMGI5MDc1MmMzZWNlYTRmM2ZmZTk2ZQ==
  nordisch.chat.registration.key: M2JhNzViOTEzY2UwNzFmZWJkZmY0Zjk1ZTg1MjE2NTA1NzgwOWQxNTM4ZGQwNWViMTc4NzM4YzRmNmIwYzhiNg==
  nordisch.chat.signing.key: ZWQyNTUxOSBhX2JNZUggRGRQbEhUc2xWNm5JV3l2L1loK3ltMlhSMnZjRE4xaUVXQlJTQ1RHSFkycw==
---
# Source: matrum/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrum-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Source: matrum/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: name-matrum
  labels:
    helm.sh/chart: matrum-0.1.0
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: synapse
      protocol: TCP
      name: synapse
  selector:
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
---
# Source: matrum/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-matrum
  labels:
    helm.sh/chart: matrum-0.1.0
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matrum
      app.kubernetes.io/instance: name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matrum
        app.kubernetes.io/instance: name
        checksum/secret: 9520f2995e
    spec:
      serviceAccountName: name-matrum
      securityContext:
        fsGroup: 991
      containers:
        - name: matrum
          securityContext:
            {}
          image: "matrixdotorg/synapse:v1.25.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: SYNAPSE_SERVER_NAME
              value: nordisch.chat
            - name: SYNAPSE_REPORT_STATS
              value: "yes"
            - name: SYNAPSE_DATA_DIR
              value: /data
            - name: SYNAPSE_CONFIG_DIR
              value: /config
          ports:
            - name: synapse
              containerPort: 8008
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: matrum-data
            - mountPath: /config
              name: matrum-secret
          livenessProbe:
            httpGet:
              port: synapse
              path: "/health"
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              port: synapse
              path: "/health"
            failureThreshold: 3
            initialDelaySeconds: 20
          resources:
            {}
      volumes:
        - name: matrum-data
          persistentVolumeClaim:
            claimName: matrum-data
        - name: matrum-secret
          secret:
            secretName: matrum-secret
---
# Source: matrum/templates/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-matrum
  labels:
    helm.sh/chart: matrum-0.1.0
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            backend:
              serviceName: name-matrum
              servicePort: 8008
---
# Source: matrum/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "name-matrum-test-connection"
  labels:
    helm.sh/chart: matrum-0.1.0
    app.kubernetes.io/name: matrum
    app.kubernetes.io/instance: name
    app.kubernetes.io/version: "v1.25.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['name-matrum:8008']
  restartPolicy: Never
