{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tainter.clusterRoleBindingName" . }}
  labels:
    {{- include "tainter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tainter.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tainter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
