apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrum.fullname" . }}
  labels:
    {{- include "matrum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: synapse
      protocol: TCP
      name: synapse
  selector:
    {{- include "matrum.selectorLabels" . | nindent 4 }}
